- name: Set fonts source directory
  set_fact:
    fonts_source: "../dotfiles/.local/share/fonts"
  tags:
    - fonts

- name: Check if Arch-specific fonts directory exists
  stat:
    path: "{{ fonts_source }}"
  tags:
    - fonts

- name: Ensure .local/share/fonts directory exists in user's home
  file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory
    mode: '0755'
  tags:
    - fonts

- name: Synchronize fonts to .local/share/fonts
  copy:
    src: "../dotfiles/"
    dest: "{{ ansible_env.HOME }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'
  tags:
    - fonts

- name: Update font cache
  command: fc-cache -f -v
  tags:
    - fonts
